# Generated by Django 4.1.4 on 2023-01-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='question',
        ),
    ]
