# Generated by Django 4.1.4 on 2023-01-04 01:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0002_rename_description_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 1, 24, 11, 242309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reentry_todo.question'),
        ),
    ]
