# Generated by Django 4.1.5 on 2023-01-05 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0003_comment_created_at_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 23, 31, 44, 136410, tzinfo=datetime.timezone.utc)),
        ),
    ]
