# Generated by Django 4.1.4 on 2023-01-11 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 0, 31, 59, 658145, tzinfo=datetime.timezone.utc)),
        ),
    ]
