# Generated by Django 4.1.5 on 2023-01-12 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0006_tag_alter_comment_created_at_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 19, 51, 55, 328129, tzinfo=datetime.timezone.utc)),
        ),
    ]
