# Generated by Django 4.1.5 on 2023-01-12 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0007_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 20, 14, 7, 468378, tzinfo=datetime.timezone.utc)),
        ),
    ]
