# Generated by Django 4.1.5 on 2023-01-13 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0008_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 0, 40, 40, 180414, tzinfo=datetime.timezone.utc)),
        ),
    ]
