# Generated by Django 4.1.4 on 2023-02-21 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0009_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 29, 54, 286978, tzinfo=datetime.timezone.utc)),
        ),
    ]
