# Generated by Django 4.1.4 on 2023-03-02 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0010_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 15, 39, 32, 236684, tzinfo=datetime.timezone.utc)),
        ),
    ]
