# Generated by Django 4.1.4 on 2023-02-12 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0010_resource_alter_comment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 23, 28, 56, 365733, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='resourcepages',
            name='sub_category',
            field=models.ManyToManyField(to='reentry_todo.sub'),
        ),
    ]
