# Generated by Django 4.1.4 on 2023-02-12 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reentry_todo', '0011_resourcepages_sub_delete_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 23, 38, 0, 869710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ResourcePages',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
